# This rule is not used by the project controller-test itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the compute.example.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller-test
    app.kubernetes.io/managed-by: kustomize
  name: ec2instance-editor-role
rules:
- apiGroups:
  - compute.example.com
  resources:
  - ec2instances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.example.com
  resources:
  - ec2instances/status
  verbs:
  - get
