# This rule is not used by the project controller-test itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over compute.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller-test
    app.kubernetes.io/managed-by: kustomize
  name: ec2instance-admin-role
rules:
- apiGroups:
  - compute.example.com
  resources:
  - ec2instances
  verbs:
  - '*'
- apiGroups:
  - compute.example.com
  resources:
  - ec2instances/status
  verbs:
  - get
